version: '3.8'
services:
  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: whisper-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - WHISPER_MODEL=Zoont/faster-whisper-large-v3-turbo-int8-ct2
      - WHISPER_COMPUTE_TYPE=int8
      - WHISPER_DEVICE=cpu
      - GRADIO_ANALYTICS_ENABLED=false
      - HF_HUB_DISABLE_TELEMETRY=1
      - DO_NOT_TRACK=1
    volumes:
      - whisper_models:/root/.cache/huggingface
volumes:
  whisper_models:
